{% set name = "langchain-text-splitters" %}
{% set version = "1.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
  sha256: 782a723db0a4746ac91e251c7c1d57fd23636e4f38ed733074e28d7a86f41627
  patches:
    - patches/0001-update-conftest.patch

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - langchain-core >=1.2.31,<2.0.0
  run_constrained:
    # typing
    - mypy >=1.19.1,<1.20.0
    - lxml-stubs >=0.5.1,<1.0.0
    - types-requests >=2.31.0.20240218,<3.0.0.0
    - tiktoken >=0.8.0,<1.0.0
    - beautifulsoup4 >=4.13.5,<5.0.0

test:
  source_files:
    - tests
  imports:
    - langchain_text_splitters
  requires:
    - pip
    - pytest >=8.0.0,<9.0.0
    - freezegun>=1.2.2,<2.0.0
    - nltk >=3.9.1,<4.0.0
    - lxml >=4.9.3,<7.0.0
    - beautifulsoup4 >=4.13.5,<5.0.0
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests/unit_tests/  # [py<314]
    - pytest -v tests --ignore=tests/integration_tests/test_text_splitter.py  # [py==314]

about:
  home: https://github.com/langchain-ai/langchain
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/text-splitters
  doc_url: https://reference.langchain.com/python/langchain_text_splitters/
  summary: LangChain text splitting utilities
  description: |
    LangChain Text Splitters contains utilities for splitting
    into chunks a wide variety of text documents.
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - pavelzw
