{% set name = "langchain-text-splitters" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
  sha256: 7a50a04ada9a133bbabb80731df7f6ddac51bc9f1b9cab7fa09304d71d38a6cc
  patches:
    - patches/0001-update-conftest.patch

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - pdm-backend
    - pip
  run:
    - python
    - langchain-core <2.0.0,>=0.3.75
  run_constrained:
    - mypy <1.18,>=1.17.1
    - lxml-stubs <1.0.0,>=0.5.1
    - types-requests <3.0.0.0,>=2.31.0.20240218
    - tiktoken <1.0.0,>=0.8.0

test:
  source_files:
    - tests
  imports:
    - langchain_text_splitters
    - langchain_text_splitters.base
    - langchain_text_splitters.character
    - langchain_text_splitters.html
    - langchain_text_splitters.json
    - langchain_text_splitters.jsx
    - langchain_text_splitters.konlpy
    - langchain_text_splitters.latex
    - langchain_text_splitters.markdown
    - langchain_text_splitters.nltk
    - langchain_text_splitters.python
    - langchain_text_splitters.sentence_transformers
    - langchain_text_splitters.spacy
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
  requires:
    - pip
    - pytest
    - lxml
    - bs4
    - nltk

about:
  home: https://github.com/langchain-ai/langchain
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/text-splitters
  doc_url: https://python.langchain.com/v0.1/docs/modules/data_connection/document_transformers/
  summary: LangChain text splitting utilities
  description: |
    LangChain Text Splitters contains utilities for splitting
    into chunks a wide variety of text documents.
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - pavelzw
