{% set name = "langchain-text-splitters" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
  sha256: 75e58acb7585dc9508f3cd9d9809cb14751283226c2d6e21fb3a9ae57582ca22
  patches:
    - patches/0001-update-conftest.patch

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - langchain-core >=1.2.0,<2.0.0
  run_constrained:
    - lxml >=4.9.3,<6.0.0
    - beautifulsoup4 >=4.12.3,<5.0.0

test:
  source_files:
    - tests
  imports:
    - langchain_text_splitters
  requires:
    - pip
    - pytest >=8.0.0,<9.0.0
    - pytest-mock >=3.10.0,<4.0.0
    - pytest-socket >=0.7.0,<1.0.0
    - pytest-xdist >=3.6.1,<4.0.0
    - freezegun>=1.2.2,<2.0.0
    - nltk >=3.9.1,<4.0.0
    - spacy >=3.8.7,<4.0.0  # [py<314]
    - thinc >=8.3.6,<9.0.0  # [py<314]
    # transformers is not available for python 3.14
    - transformers >=4.51.3,<5.0.0  # [py<314]
    # - sentence-transformers>=3.0.1,<4.0.0  # [py<314]
    # - tiktoken >=0.8.0,<1.0.0  # [py<314]
    # - scipy >=1.7.0,<2.0.0  # [py<313]
    # - scipy >=1.14.1,<2.0.0  # [py>=313]
    # 'en-core-web-sm' from spacy-models is required for the tests.
    # - spacy-models
    # lxml and bs4 are not mentioned in the dependencies, but it is required for the tests
    - bs4
    - lxml
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests  # [py<314]
    - pytest -v tests --ignore=tests/integration_tests/test_text_splitter.py  # [py==314]

about:
  home: https://github.com/langchain-ai/langchain
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/text-splitters
  doc_url: https://reference.langchain.com/python/langchain_text_splitters/
  summary: LangChain text splitting utilities
  description: |
    LangChain Text Splitters contains utilities for splitting
    into chunks a wide variety of text documents.
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - pavelzw
